SORTING_QUESTIONS = [
    
    {
        "id": "capitals",
        "title": "Capitals",
        "prompt": 'Sort these capitals from north top to south bottom',
        "criterion": "latitude",
        "direction": "asc",
        "labels": {"more": "south", "less": "north"},
        "start_id": "bern",
        "items": [
            {"id": "stockholm ", "idx": 0, "label": "Stockholm", "value": "59°19’", "unit": "N"},
            {"id": "berlin", "idx": 1, "label": "Berlin", "value": "52°31’", "unit": "N"},
            {"id": "london", "idx": 2, "label": "London", "value": "51°30’", "unit": "N"},
            {"id": "budapest", "idx": 3, "label": "Budapest", "value": "47°29’", "unit": "N"},
            {"id": "bern", "idx": 4, "label": "Bern", "value": "46°56’", "unit": "N"},
            {"id": "beijing", "idx": 5, "label": "Beijing", "value": "39°54’", "unit": "N"},
            {"id": "washington", "idx": 6, "label": "Washington, D.C.", "value": "38°54’", "unit": "N"},
            {"id": "cape_town", "idx": 7, "label": "Cape Town", "value": "33°55’", "unit": "S"},
            {"id": "wellington", "idx": 8, "label": "Wellington", "value": "35°17’", "unit": "S"},
        ],
    },
    
    {
        "id": "animals",
        "title": "Fictional animals",
        "prompt": 'Sort these fictional animals alphabetically by the first name of their owners from A top to Z bottom',
        "criterion": "Alphabet",
        "direction": "asc",
        "labels": {"more": "Z", "less": "A"},
        "start_id": "snoopy",
        "items": [
            {"id": "appa", "idx": 0, "label": "Appa", "value": "Aang", "unit": ""},
            {"id": "dug", "idx": 1, "label": "Dug", "value": "Carl", "unit": ""},
            {"id": "snoopy", "idx": 2, "label": "Snoopy", "value": "Charlie Brown", "unit": ""},
            {"id": "toto", "idx": 3, "label": "Toto", "value": "Dorothy", "unit": ""},
            {"id": "azrael", "idx": 4, "label": "Azrael", "value": "Gargamel", "unit": ""},
            {"id": "crookshanks", "idx": 5, "label": "Crookshanks", "value": "Hermione Granger", "unit": ""},
            {"id": "garfield", "idx": 6, "label": "Garfield", "value": "Jon Arbuckle", "unit": ""},
            {"id": "pluto", "idx": 7, "label": "Pluto", "value": "Mickey Mouse", "unit": ""},
            {"id": "idefix", "idx": 8, "label": "Idefix", "value": "Obelix", "unit": ""},
        ],
    },
    
    {
        "id": "national_days",
        "title": "National days",
        "prompt": 'Sort these national days by the year of the event they are celebrating (not the year they were first celebrated!) from early top to late bottom',
        "criterion": "year",
        "direction": "asc",
        "labels": {"more": "recently", "less": "long ago"},
        "start_id": "germany",
        "items": [
            {"id": "switzerland", "label": "Switzerland's Bundesfeiertag", "value": 1291, "unit": ""},
            {"id": "usa", "label": "USA's Independence Day", "value": 1776, "unit": ""},
            {"id": "france", "label": "France's Bastille Day", "value": 1789, "unit": ""},
            {"id": "finland", "label": "Finland's Independence Day", "value": 1917, "unit": ""},
            {"id": "turkey", "label": "Turkey's Republic Day", "value": 1923, "unit": ""},
            {"id": "italy", "label": "Italy's Festa della Repubblica", "value": 1946, "unit": ""},
            {"id": "kyrgyzstan", "label": "Kyrgyzstan's Independence Day", "value": 1991, "unit": ""},
            {"id": "germany", "label": "Germany's Unity Day", "value": 1990, "unit": ""},
            {"id": "south_africa", "label": "South Africa's Freedom Day", "value": 1994, "unit": ""},
        ],
    },

    {
        "id": "playing_fields",
        "title": "Playing Fields",
        "prompt": 'Sort the playing fields of these sports by their surface area from large top to small bottom.',
        "criterion": "Field size",
        "direction": "desc",
        "labels": {"more": "large", "less": "small"},
        "start_id": "tennis",
        "items": [
            {"id": "football", "label": "Football (FIFA)", "value": 7140, "unit": "m2"},
            {"id": "american_football", "label": "American football", "value": 4456, "unit": "m2"},
            {"id": "field_hockey", "label": "Field hockey", "value": 5027, "unit": "m2"},
            {"id": "ice_hockey", "label": "Ice hockey (Olympic)", "value": 1784, "unit": "m2"},
            {"id": "basketball", "label": "Basketball (Olympic)", "value": 420, "unit": "m2"},
            {"id": "tennis", "label": "Tennis (double)", "value": 260, "unit": "m2"},
            {"id": "curling", "label": "Curling", "value": 217, "unit": "m2"},
            {"id": "volleyball", "label": "Volleyball", "value": 162, "unit": "m2"},
            {"id": "badminton", "label": "Badminton", "value": 82, "unit": "m2"},
        ],
    },

    {
        "id": "bands",
        "title": "Bands",
        "prompt": 'Sort these musical groups by the number of members they currently have (or had when disbanded), from few top to many bottom',
        "criterion": "members",
        "direction": "asc",
        "labels": {"more": "many", "less": "few"},
        "start_id": "abba",
        "items": [
            {"id": "daftpunk ", "label": "Daft Punk", "value": 2, "unit": ""},
            {"id": "police", "label": "The Police", "value": 3, "unit": ""},
            {"id": "abba", "label": "ABBA", "value": 4, "unit": ""},
            {"id": "backstreet", "label": "Backstreet Boys", "value": 5, "unit": ""},
            {"id": "rammstein", "label": "Rammstein", "value": 6, "unit": ""},
            {"id": "owl city", "label": "Owl City", "value": 1, "unit": ""},
            {"id": "bts", "label": "BTS", "value": 7, "unit": ""},
            {"id": "earth", "label": "Earth, Wind & Fire", "value": 9, "unit": ""},
            {"id": "clan", "label": "Wu-Tang Clan", "value": 10, "unit": ""},
        ],
    },

    {
        "id": "cars",
        "title": "Cars",
        "prompt": 'Sort these car brands by popularity in Switzerland, as measured by the number of new registrations in 2025, from popular top to unpopular bottom',
        "criterion": "registrations",
        "direction": "desc",
        "labels": {"more": "popular", "less": "unpopular"},
        "start_id": "porsche",
        "items": [
            {"id": "vw ", "label": "Volkswagen", "value": 25618, "unit": ""},
            {"id": "skoda", "label": "Skoda", "value": 22297, "unit": ""},
            {"id": "bmw", "label": "BMW", "value": 20480, "unit": ""},
            {"id": "audi", "label": "Audi", "value": 17227, "unit": ""},
            {"id": "hyundai", "label": "Hyundai", "value": 9374, "unit": ""},
            {"id": "tesla", "label": "Tesla", "value": 6460, "unit": ""},
            {"id": "volvo", "label": "Volvo", "value": 8607, "unit": ""},
            {"id": "porsche", "label": "Porsche", "value": 4315, "unit": ""},
            {"id": "citroen", "label": "Citroen", "value": 2746, "unit": ""},
        ],
    },
    
    {
        "id": "movies_oscar",
        "title": "Movies",
        "prompt": 'Sort these movies by the year they won "Best Picture" at the Academy Awards, from early top to recent bottom.',
        "criterion": "Best Picture year",
        "direction": "asc",
        "labels": {"more": "recently", "less": "long ago"},
        "start_id": "titanic",
        "items": [
            {"id": "godfather", "label": "The Godfather", "value": 1972, "unit": ""},
            {"id": "rocky", "label": "Rocky", "value": 1976, "unit": ""},
            {"id": "lambs", "label": "The Silence of the Lambs", "value": 1991, "unit": ""},
            {"id": "gump", "label": "Forrest Gump", "value": 1994, "unit": ""},
            {"id": "titanic", "label": "Titanic", "value": 1997, "unit": ""},
            {"id": "gladiator", "label": "Gladiator", "value": 2000, "unit": ""},
            {"id": "baby", "label": "Million Dollar Baby", "value": 2004, "unit": ""},
            {"id": "slave", "label": "12 Years a Slave", "value": 2013, "unit": ""},
            {"id": "benhur", "label": "Ben Hur", "value": 1959, "unit": ""},
        ],
    },

    {
        "id": "mountains_prominence",
        "title": "Peak Prominence",
        "prompt": "Sort these peaks by prominence (height above saddle to a higher peak on the same landmass), from high (top) to low (bottom).",
        "criterion": "Prominence (m)",
        "labels": {"more": "taller", "less": "shorter"},
        "direction": "desc",
        "start_id": "kilimanjaro",
        "items": [
            {"id": "kilimanjaro", "label": "Mount Kilimanjaro", "value": 5895, "unit": "m"},
            {"id": "maunakea", "label": "Mauna Kea", "value": 4207, "unit": "m"},
            {"id": "k2", "label": "K2", "value": 4020, "unit": "m"},
            {"id": "fuji", "label": "Mount Fuji", "value": 3776, "unit": "m"},
            {"id": "zugspitze", "label": "Zugspitze", "value": 1746, "unit": "m"},
            {"id": "vesuvius", "label": "Mount Vesuvius", "value": 1232, "unit": "m"},
            {"id": "matterhorn", "label": "Matterhorn", "value": 1040, "unit": "m"},
            {"id": "sugarloaf", "label": "Sugarloaf Mountain", "value": 396, "unit": "m"},
        ],
    }
]


QUESTIONS_BY_MODE = {
    "sorting": SORTING_QUESTIONS,
}